# Generated by Django 4.2.11 on 2024-06-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auths", "0002_alter_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
